# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_grabber_gui_02.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1650, 1040)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(290, 800, 291, 120))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_y1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_y1.setObjectName("lineEdit_y1")
        self.gridLayout_2.addWidget(self.lineEdit_y1, 2, 2, 1, 1)
        self.btn_x1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_x1.setObjectName("btn_x1")
        self.gridLayout_2.addWidget(self.btn_x1, 0, 1, 1, 1)
        self.btn_x2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_x2.setObjectName("btn_x2")
        self.gridLayout_2.addWidget(self.btn_x2, 1, 1, 1, 1)
        self.btn_y1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_y1.setObjectName("btn_y1")
        self.gridLayout_2.addWidget(self.btn_y1, 2, 1, 1, 1)
        self.btn_y2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_y2.setObjectName("btn_y2")
        self.gridLayout_2.addWidget(self.btn_y2, 3, 1, 1, 1)
        self.lineEdit_x2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_x2.setObjectName("lineEdit_x2")
        self.gridLayout_2.addWidget(self.lineEdit_x2, 1, 2, 1, 1)
        self.lineEdit_y2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_y2.setObjectName("lineEdit_y2")
        self.gridLayout_2.addWidget(self.lineEdit_y2, 3, 2, 1, 1)
        self.lineEdit_x1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_x1.setObjectName("lineEdit_x1")
        self.gridLayout_2.addWidget(self.lineEdit_x1, 0, 2, 1, 1)
        self.checkBox_log_x = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_log_x.setObjectName("checkBox_log_x")
        self.gridLayout_2.addWidget(self.checkBox_log_x, 0, 0, 1, 1)
        self.checkBox_log_y = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_log_y.setObjectName("checkBox_log_y")
        self.gridLayout_2.addWidget(self.checkBox_log_y, 2, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 790, 160, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_reset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_reset.setObjectName("btn_reset")
        self.verticalLayout.addWidget(self.btn_reset)
        self.btn_load = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_load.setObjectName("btn_load")
        self.verticalLayout.addWidget(self.btn_load)
        self.btn_clear_image = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_clear_image.setObjectName("btn_clear_image")
        self.verticalLayout.addWidget(self.btn_clear_image)
        self.btn_delete_data = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_delete_data.setObjectName("btn_delete_data")
        self.verticalLayout.addWidget(self.btn_delete_data)
        self.btn_print_data = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_print_data.setObjectName("btn_print_data")
        self.verticalLayout.addWidget(self.btn_print_data)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(840, 786, 131, 21))
        self.label_status.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.infobox = QtWidgets.QTextBrowser(self.centralwidget)
        self.infobox.setGeometry(QtCore.QRect(620, 810, 181, 141))
        self.infobox.setObjectName("infobox")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 780, 281, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 920, 331, 41))
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 10, 1261, 731))
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 411, 271))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(1350, 20, 271, 771))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(1400, 810, 211, 145))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.btn_GetDataPoints = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn_GetDataPoints.setObjectName("btn_GetDataPoints")
        self.gridLayout_6.addWidget(self.btn_GetDataPoints, 1, 0, 1, 1)
        self.lineEdit_Rounding = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Rounding.sizePolicy().hasHeightForWidth())
        self.lineEdit_Rounding.setSizePolicy(sizePolicy)
        self.lineEdit_Rounding.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_Rounding.setObjectName("lineEdit_Rounding")
        self.gridLayout_6.addWidget(self.lineEdit_Rounding, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 4, 0, 1, 1)
        self.lineEdit_DataPoints = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_DataPoints.sizePolicy().hasHeightForWidth())
        self.lineEdit_DataPoints.setSizePolicy(sizePolicy)
        self.lineEdit_DataPoints.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_DataPoints.setObjectName("lineEdit_DataPoints")
        self.gridLayout_6.addWidget(self.lineEdit_DataPoints, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_pixel_color = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_pixel_color.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pixel_color.setText("")
        self.label_pixel_color.setObjectName("label_pixel_color")
        self.gridLayout_6.addWidget(self.label_pixel_color, 2, 1, 1, 1)
        self.btn_ClearTable = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn_ClearTable.setObjectName("btn_ClearTable")
        self.gridLayout_6.addWidget(self.btn_ClearTable, 0, 0, 1, 1)
        self.btn_CopyData = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn_CopyData.setObjectName("btn_CopyData")
        self.gridLayout_6.addWidget(self.btn_CopyData, 0, 1, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(1230, 810, 163, 112))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btn_TopRight = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn_TopRight.setObjectName("btn_TopRight")
        self.gridLayout_7.addWidget(self.btn_TopRight, 2, 0, 1, 1)
        self.btn_BottomLeft = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn_BottomLeft.setObjectName("btn_BottomLeft")
        self.gridLayout_7.addWidget(self.btn_BottomLeft, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.btn_ClearExtractionLimits = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn_ClearExtractionLimits.setObjectName("btn_ClearExtractionLimits")
        self.gridLayout_7.addWidget(self.btn_ClearExtractionLimits, 3, 0, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(840, 820, 190, 128))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_y_extract = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_y_extract.setFont(font)
        self.label_y_extract.setFrameShape(QtWidgets.QFrame.Box)
        self.label_y_extract.setObjectName("label_y_extract")
        self.gridLayout.addWidget(self.label_y_extract, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_x_extract = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_x_extract.setFont(font)
        self.label_x_extract.setFrameShape(QtWidgets.QFrame.Box)
        self.label_x_extract.setObjectName("label_x_extract")
        self.gridLayout.addWidget(self.label_x_extract, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_x_select = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_x_select.setFrameShape(QtWidgets.QFrame.Box)
        self.label_x_select.setObjectName("label_x_select")
        self.gridLayout.addWidget(self.label_x_select, 0, 1, 1, 1)
        self.label_y_select = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_y_select.setFrameShape(QtWidgets.QFrame.Box)
        self.label_y_select.setObjectName("label_y_select")
        self.gridLayout.addWidget(self.label_y_select, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1650, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_x1.setText(_translate("MainWindow", "x-1"))
        self.btn_x2.setText(_translate("MainWindow", "x-2"))
        self.btn_y1.setText(_translate("MainWindow", "y-1"))
        self.btn_y2.setText(_translate("MainWindow", "y-2"))
        self.checkBox_log_x.setText(_translate("MainWindow", "Log"))
        self.checkBox_log_y.setText(_translate("MainWindow", "Log"))
        self.btn_reset.setText(_translate("MainWindow", "Reset"))
        self.btn_load.setText(_translate("MainWindow", "Load image"))
        self.btn_clear_image.setText(_translate("MainWindow", "Clear image"))
        self.btn_delete_data.setText(_translate("MainWindow", "Delete last point"))
        self.btn_print_data.setText(_translate("MainWindow", "Print data"))
        self.label_status.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "Calibration:"))
        self.label_7.setText(_translate("MainWindow", "After calibration, click right mouse button to manually add data point to table."))
        self.label_8.setText(_translate("MainWindow", "Color of curve"))
        self.btn_GetDataPoints.setText(_translate("MainWindow", "Get data points"))
        self.lineEdit_Rounding.setText(_translate("MainWindow", "3"))
        self.label_10.setText(_translate("MainWindow", "# of decimals"))
        self.lineEdit_DataPoints.setText(_translate("MainWindow", "30"))
        self.label_9.setText(_translate("MainWindow", "# of data points"))
        self.btn_ClearTable.setText(_translate("MainWindow", "Clear table"))
        self.btn_CopyData.setText(_translate("MainWindow", "Export"))
        self.btn_TopRight.setText(_translate("MainWindow", "Top right"))
        self.btn_BottomLeft.setText(_translate("MainWindow", "Bottom left"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Data extraction limits:</span></p></body></html>"))
        self.btn_ClearExtractionLimits.setText(_translate("MainWindow", "Clear limits"))
        self.label_5.setText(_translate("MainWindow", "y :"))
        self.label_y_extract.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "x [px]:"))
        self.label_4.setText(_translate("MainWindow", "x :"))
        self.label_x_extract.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "y [px]:"))
        self.label_x_select.setText(_translate("MainWindow", "TextLabel"))
        self.label_y_select.setText(_translate("MainWindow", "TextLabel"))
